name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或 master，根據您的預設分支名稱調整

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-cache: 'npm'
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 將編譯後的 dist 資料夾內容部署到 gh-pages 分支
          branch: gh-pages # 部署的目標分支
          clean: true
